import { defineConfig } from 'tailwindcss'

export default defineConfig({
  content: [
    // Vite root is 'src/', so paths are relative to that
    './**/*.{js,ts,jsx,tsx}',
    './index.html',
    // Session processing package source files (via symlink in app's node_modules)
    '../node_modules/@guideai-dev/session-processing/src/**/*.{js,ts,jsx,tsx}',
    // Session processing package built files
    '../node_modules/@guideai-dev/session-processing/dist/esm/**/*.{js,jsx}',
  ],
  // Safelist: These classes are needed because:
  // 1. DaisyUI component base classes (card, stat, etc.) - required for v4 compatibility
  // 2. DaisyUI variant classes generated dynamically (btn-xs, badge-ghost, etc.)
  // 3. Some classes are used conditionally or constructed dynamically in components
  // 4. Classes from shared packages may not be detected during the build process
  safelist: [
    // DaisyUI Component Base Classes - Essential for components to work
    'card',
    'card-body',
    'card-title',
    'card-actions',
    'stat',
    'stat-title',
    'stat-value',
    'stat-desc',
    'stat-figure',
    'stat-actions',
    'checkbox',
    'checkbox-sm',
    'input',
    'select',
    'textarea',
    'tooltip',
    'tooltip-left',
    'tooltip-right',
    'tooltip-top',
    'tooltip-bottom',


    // Purple classes for AI Assistant button
    'text-purple-700',
    'bg-purple-50',
    'border-purple-200',
    'hover:bg-purple-100',
    'focus:ring-purple-500',
    'text-purple-600',
    'text-purple-800',
    'bg-purple-100',
    'bg-purple-200',
    'border-purple-300',
    'hover:bg-purple-200',
    'focus:ring-purple-400',
    'focus:ring-purple-600',

    // Blue classes used throughout drizzle-cube
    'bg-blue-50',
    'bg-blue-100',
    'bg-blue-500',
    'bg-blue-600',
    'text-blue-600',
    'text-blue-700',
    'text-blue-800',
    'text-blue-900',
    'border-blue-200',
    'border-blue-300',
    'border-blue-500',
    'border-blue-600',
    'hover:bg-blue-50',
    'hover:bg-blue-100',
    'hover:bg-blue-200',
    'hover:bg-blue-600',
    'hover:bg-blue-700',
    'hover:text-blue-800',
    'hover:text-blue-900',
    'focus:ring-blue-500',
    'focus:border-blue-500',
    'border-b-2',
    'border-blue-600',
    'ring-2',
    'ring-blue-500',
    'ring-blue-600',
    'ring-offset-1',
    'scale-110',

    // Gray classes for modals and UI elements
    'bg-gray-50',
    'bg-gray-100',
    'bg-gray-200',
    'bg-gray-300',
    'bg-gray-400',
    'text-gray-400',
    'text-gray-500',
    'text-gray-600',
    'text-gray-700',
    'text-gray-800',
    'text-gray-900',
    'border-gray-200',
    'border-gray-300',
    'border-gray-400',
    'hover:bg-gray-50',
    'hover:bg-gray-100',
    'hover:bg-gray-200',
    'hover:text-gray-600',
    'hover:text-gray-700',
    'hover:text-gray-800',
    'hover:text-gray-900',
    'hover:border-gray-300',
    'hover:border-gray-400',

    // Green classes for success states
    'bg-green-50',
    'bg-green-100',
    'bg-green-500',
    'bg-green-600',
    'text-green-500',
    'text-green-600',
    'text-green-700',
    'text-green-800',
    'border-green-200',
    'border-green-500',
    'border-green-600',
    'border-green-700',
    'hover:bg-green-200',
    'hover:bg-green-700',
    'hover:text-green-900',
    'focus:ring-green-500',

    // DaisyUI semantic color backgrounds with opacity
    'bg-success/10',
    'bg-success/20',
    'bg-warning/10',
    'bg-warning/20',
    'bg-error/10',
    'bg-error/20',
    'bg-info/10',
    'bg-info/20',

    // DaisyUI semantic border colors for timeline messages
    'border-l-info',
    'border-l-primary',
    'border-l-secondary',
    'border-l-warning',
    'border-l-error',
    'border-l-accent',
    'border-l-neutral',

    // Red classes for error states
    'bg-red-50',
    'bg-red-100',
    'bg-red-500',
    'bg-red-600',
    'text-red-500',
    'text-red-600',
    'text-red-700',
    'text-red-800',
    'border-red-200',
    'border-red-300',
    'border-red-500',
    'hover:bg-red-100',
    'hover:bg-red-200',
    'hover:bg-red-700',
    'hover:text-red-600',
    'hover:text-red-900',

    // Phase timeline color classes (for session-processing package)
    // Text colors for phase types
    'text-blue-500',
    'text-blue-600',
    'text-purple-500',
    'text-purple-600',
    'text-pink-500',
    'text-pink-600',
    'text-green-500',
    'text-green-600',
    'text-lime-500',
    'text-lime-600',
    'text-orange-500',
    'text-orange-600',
    'text-red-500',
    'text-red-600',
    'text-cyan-500',
    'text-cyan-600',
    'text-yellow-500',
    'text-yellow-600',
    'text-gray-500',
    'text-gray-600',
    // Border colors for phase types
    'border-blue-500',
    'border-blue-600',
    'border-purple-500',
    'border-purple-600',
    'border-pink-500',
    'border-pink-600',
    'border-green-500',
    'border-green-600',
    'border-lime-500',
    'border-lime-600',
    'border-orange-500',
    'border-orange-600',
    'border-red-500',
    'border-red-600',
    'border-cyan-500',
    'border-cyan-600',
    'border-yellow-500',
    'border-yellow-600',
    'border-gray-500',
    'border-gray-600',
    // Background colors with opacity for phase types
    'bg-blue-500/10',
    'bg-blue-500/20',
    'bg-purple-500/10',
    'bg-purple-500/20',
    'bg-pink-500/10',
    'bg-pink-500/20',
    'bg-green-500/10',
    'bg-green-500/20',
    'bg-lime-500/10',
    'bg-lime-500/20',
    'bg-orange-500/10',
    'bg-orange-500/20',
    'bg-red-500/10',
    'bg-red-500/20',
    'bg-cyan-500/10',
    'bg-cyan-500/20',
    'bg-yellow-500/10',
    'bg-yellow-500/20',
    'bg-gray-500/10',
    'bg-gray-500/20',

    // Responsive modal classes
    'w-full',
    'h-full',
    'md:w-[90vw]',
    'md:h-[90vh]',
    'max-w-none',
    'rounded-none',
    'md:rounded-lg',
    'flex',
    'md:flex',
    'md:items-center',
    'md:justify-center',

    // Responsive breakpoint classes
    'sm:flex',
    'sm:flex-row',
    'sm:items-center',
    'sm:flex-initial',
    'sm:w-32',
    'sm:w-40',
    'sm:justify-start',
    'sm:p-4',
    'sm:text-lg',
    'sm:gap-1',
    'sm:gap-2',
    'sm:inline',
    'sm:mb-1',
    'md:flex',
    'md:flex-row',
    'md:flex-nowrap',
    'md:items-center',
    'md:items-start',
    'md:justify-between',
    'md:gap-2',
    'md:gap-3',
    'md:gap-4',
    'md:px-4',
    'md:py-3',
    'md:px-6',
    'md:py-3',
    'md:w-6',
    'md:h-6',
    'md:w-80',
    'md:pl-12',
    'md:cols-3',
    'md:grid-cols-3',
    'lg:w-96',
    'lg:inline',
    'hidden',
    'md:hidden',
    'md:inline',
    'md:flex',

    // Layout and spacing classes
    'flex-col',
    'flex-row',
    'items-center',
    'items-start',
    'justify-center',
    'justify-between',
    'justify-end',
    'space-x-1',
    'space-x-2',
    'space-x-3',
    'space-y-1',
    'space-y-4',
    'gap-1',
    'gap-2',
    'gap-3',
    'gap-4',
    'min-w-0',
    'min-w-max',
    'max-w-md',
    'max-w-2xl',
    'max-w-none',
    'flex-1',
    'shrink-0',
    'truncate',

    // Sizing classes
    'w-1',
    'w-1.5',
    'w-2',
    'w-3',
    'w-4',
    'w-5',
    'w-6',
    'w-7',
    'w-8',
    'w-12',
    'w-16',
    'w-48',
    'w-72',
    'h-1',
    'h-2',
    'h-3',
    'h-4',
    'h-5',
    'h-6',
    'h-7',
    'h-8',
    'h-12',
    'h-16',
    'min-h-64',

    // Positioning classes
    'absolute',
    'relative',
    'fixed',
    'z-9999',
    'z-10',
    'z-20',
    'z-30',
    'z-50',
    'inset-0',
    'top-0',
    'top-full',
    '-top-2',
    'left-0',
    'right-0',
    '-right-2',
    'bottom-0',

    // Border and shadow classes
    'border',
    'border-2',
    'border-t',
    'border-b',
    'border-dashed',
    'border-success',
    'rounded',
    'rounded-sm',
    'rounded-md',
    'rounded-lg',
    'rounded-full',
    'rounded-t-lg',
    'shadow',
    'shadow-xs',
    'shadow-md',
    'shadow-lg',
    'shadow-success/20',
    'shadow-success/30',

    // Animation and transition classes
    'animate-spin',
    'animate-pulse',
    'transition-all',
    'transition-colors',
    'duration-200',
    'ease-in-out',

    // Typography classes
    'text-xs',
    'text-sm',
    'text-base',
    'text-lg',
    'text-xl',
    'font-medium',
    'font-semibold',
    'font-bold',
    'font-mono',
    'leading-tight',
    'leading-none',
    'whitespace-pre-wrap',
    'overflow-auto',
    'overflow-hidden',
    'overflow-y-auto',
    'line-clamp-2',

    // State classes
    'cursor-pointer',
    'cursor-not-allowed',
    'disabled:opacity-50',
    'disabled:cursor-not-allowed',
    'disabled:bg-gray-300',
    'focus:outline-hidden',
    'focus:ring-2',
    'focus:ring-offset-2',
    'hover:scale-110',

    // Grid and layout utilities
    'grid',
    'grid-cols-1',
    'grid-cols-2',
    'grid-cols-3',
    'grid-cols-5',
    'sm:grid-cols-2',
    'lg:grid-cols-2',
    'lg:grid-cols-5',
    'resize-y',
    'resize-none',

    // Other utility classes
    'mx-auto',
    'mb-1',
    'mb-2',
    'mb-3',
    'mb-4',
    'mt-1',
    'mt-2',
    'mt-4',
    'p-1',
    'p-1.5',
    'p-2',
    'p-3',
    'p-4',
    'p-6',
    'p-8',
    'px-1',
    'px-2',
    'px-3',
    'px-4',
    'px-6',
    'py-1',
    'py-2',
    'py-3',
    'py-4',
    'px-1.5',
    'py-0.5',
    'px-2',
    'py-1',
    'px-3',
    'py-1.5',
    'px-4',
    'py-2',
    'm-0.5',
    'mr-1',
    'mr-1.5',
    'mr-2',
    'ml-1',
    'ml-2',
    'ml-1.5',
    '-mr-2',
    'text-center',
    'text-left',
    'italic',
    'underline',
    'break-words',
    'overflow-x-auto',
    'max-h-20',
    'max-h-32',
    'max-h-60',
    'max-h-64',
    'max-h-80',

    // QuickRatingPopover positioning
    '-translate-x-1/2',
    '-translate-y-1/2',
    'translate-x-1/2',
    'translate-y-1/2',
    'bottom-full',
    'top-full',
    'left-1/2',
    'right-1/2',
    'mt-px',
    'mb-px',
    'border-l-4',
    'border-r-4',
    'border-t-4',
    'border-b-4',
    'border-l-transparent',
    'border-r-transparent',
    'border-t-transparent',
    'border-b-transparent',
    'border-t-base-300',
    'border-b-base-300',

    // DaisyUI button variants for QuickRatingPopover
    'btn-xs',
    'btn-sm',
    'btn-square',
    'btn-error',
    'btn-warning',
    'btn-success',
    'btn-secondary',
    'btn-ghost',

    // DaisyUI badge variants for RatingBadge and timeline messages
    'badge-ghost',
    'badge-success',
    'badge-warning',
    'badge-error',
    'badge-neutral',
    'badge-accent',
    'badge-secondary',
    'badge-sm',
    'badge-lg',
  ],
  theme: {
    extend: {},
  },
  plugins: [],
})
